AllCops:
  UseCache: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.5.3

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - extend
      - include
      - prepend
    attributes:
      - attr_accessor
      - attr_reader
      - attr_writer
  ExpectedOrder:
    - constants
    - module_inclusion
    - attributes
    - public_class_methods
    - initializer
    - public_methods
    - predicates
    - protected_methods
    - private_methods

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentFirstArgument:
  EnforcedStyle: consistent_relative_to_receiver

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineOperationIndentation:
  Enabled: false # Waiting for e.g. `indented_relative_to_receiver`.

Lint/AmbiguousOperator:
  Enabled: false # Conflicts with other rules.

Lint/AmbiguousRegexpLiteral:
  Enabled: false # Conflicts with other rules.

Lint/Void:
  CheckForMethodsWithNoSideEffects: true

Metrics/BlockLength:
  ExcludedMethods:
    - new
    - describe # Tests
    - context # Tests
    - ips # Benchmarking

Metrics/ClassLength:
  Exclude:
    - "test/**/*"
    - "lib/object_inspector/formatters/templating_formatter.rb"

Metrics/LineLength:
  Max: 80
  Exclude:
    - "test/**/*"
    - "object_inspector.gemspec"

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - a
    - b

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false # Reconsider later.

Style/ClassAndModuleChildren:
  AutoCorrect: true
  Exclude:
    - "test/**/*"

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    find_all: select
    detect: detect
    inject: inject

Style/EmptyElse:
  # It"s helpful to show intent by including a comment in an else block.
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExpandPathArguments:
  Exclude:
    - "object_inspector.gemspec"

Style/FormatString:
  Enabled: false # % notation with an Array just reads better sometimes.

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: false # Allow ServiceObject.(*). Only use on classes, not instances.

Style/NumericPredicate:
  Enabled: false # Trying to be welcoming to earlier versions of Ruby.
  # AutoCorrect: true

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/ReturnNil:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/SingleLineMethods:
  Exclude:
    - "test/**/*_test.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
